### ISSUE TITLE
update with new DOI

### ISSUE THREAD

**Issue by LinguList** [lexibank/gerarditupi#19]
10.1075/dia.18032.fer

This doi is not yet active, but once the article appears. I estimate that hte article will appear in the 2021 issue, so not this year.

**Comment by LanguageStructure** [comment]
So, iwe ich es verstanden haben, diese DOI bezieht sich auf die online-first version, die in den nächsten Tagen veröffentlicht wird. Dir Druckverison tatsächlich im ersten Band 2021

**Comment by LinguList** [comment]
Die DOI wird gleich bleiben. Wir machen die concepticon-liste dann so, dass die 2021 erscheint, dann ist es sauberer. Bis dahin sind die Daten ja hier in ihrer aktuellen version.

**Comment by LanguageStructure** [comment]
Alles klar!

 VG

**Comment by MuffinLinwist** [comment]
This is already done.
