### ISSUE TITLE
Orthoprofile does not normalise combining diacritics

### ISSUE THREAD

**Issue by johenglisch** [lexibank/gerarditupi#22]
Orthoprofile does not normalise combining diacritics.  Furthermore, in some cases differently normalised segments result in different transcriptions:

https://github.com/lexibank/gerarditupi/blob/8712fcd1b7d25fee0ec49faa3a3af32f5c55d785/etc/orthography.tsv#L201

    $ sed -n -e 201p etc/orthography.tsv | cut -f1 | hexdump -ve '/1 "%02X "'
    6F CC 83 6F CC 83 0A

vs

https://github.com/lexibank/gerarditupi/blob/8712fcd1b7d25fee0ec49faa3a3af32f5c55d785/etc/orthography.tsv#L337

    $ sed -n -e 337p etc/orthography.tsv | cut -f1 | hexdump -ve '/1 "%02X "'
    C3 B5 C3 B5 0A

**Comment by LinguList** [comment]
I think this is addressed now.

**Comment by LinguList** [comment]
The normalization is not really needed, since the code normalizes, but it yields ambiguous output in the lexibank check, which is a problem, so I tried to address these cases now.

**Comment by johenglisch** [comment]
thanks (^^)
